### ISSUE TITLE
kernmagic not working with recent (5.1.0) Ipython/Jupyter version

### ISSUE THREAD

**Issue by hklemm** [rkern/kernmagic#1]
Hi,

fist of all many thanks for kernmagic, it is a really nice package. Currently however, after my last update of my python distribution, I see the following error when I start up Ipython:

```
hkl016@RWCPH23G00:~]
> ipython
65Python 2.7.11 | 64-bit | (default, Jun 11 2016, 10:32:30)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
[TerminalIPythonApp] WARNING | Error in loading extension: kernmagic
Check your config files in /pcdisk/hkl016/unix/.ipython/profile_default
Traceback (most recent call last):
  File "/mnt/ssd/apps/Enthought/User/lib/python2.7/site-packages/IPython/core/shellapp.py", line 246, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/mnt/ssd/apps/Enthought/User/lib/python2.7/site-packages/IPython/core/extensions.py", line 85, in load_extension
    if self._call_load_ipython_extension(mod):
  File "/mnt/ssd/apps/Enthought/User/lib/python2.7/site-packages/IPython/core/extensions.py", line 132, in _call_load_ipython_extension
    mod.load_ipython_extension(self.shell)
  File "/mnt/ssd/apps/Enthought/User/lib/python2.7/site-packages/kernmagic/__init__.py", line 36, in load_ipython_extension
    activate(ip)
  File "/mnt/ssd/apps/Enthought/User/lib/python2.7/site-packages/kernmagic/__init__.py", line 22, in activate
    _define_magic(ip, magic_name, getattr(mymagics, name))
  File "/mnt/ssd/apps/Enthought/User/lib/python2.7/site-packages/kernmagic/__init__.py", line 9, in _define_magic
    shell.define_magic(*args, **kwds)
AttributeError: 'TerminalInteractiveShell' object has no attribute 'define_magic'
```
Is this a known error?

**Comment by rkern** [comment]
I've updated the code to use the modern APIs.
